consul:
  image: gavinmroy/alpine-consul:0.5.2-0
  ports:
    - 8300
    - 8301
    - 8301/udp
    - 8302/udp
    - 8400
    - 8500

etcd2:
  image: slintes/etcd2:latest
    - 2379
    - 2380
    - 4001
    - 7001

